baseURL = 'https://for-my-sunshine.com.ua/'
languageCode = 'uk-ua'
title = 'For My Sunshine'
theme = 'PaperMod'

# --- БЛОК ПРИВАТНОСТІ ---
disableSitemap = true
disableKinds = ["RSS", "sitemap", "taxonomy", "term"]

# --- НАЛАШТУВАННЯ ТЕМИ ---
[params]
  env = "production"
  robots = "noindex, nofollow"
  defaultTheme = "auto"

  # Логотип зліва зверху (в меню)
  [params.label]
    text = "For My Sunshine"
    icon = "/apple-touch-icon.png"

  # Фавіконки (картинки на вкладці)
  [params.assets]
    favicon = "/favicon.ico"
    favicon16x16 = "/favicon-16x16.png"
    favicon32x32 = "/favicon-32x32.png"
    apple_touch_icon = "/apple-touch-icon.png"

# Порожнє меню (щоб не було кнопки Home)
[menu]
