baseURL = 'https://for-my-sunshine.com.ua/'
languageCode = 'uk-ua'
title = 'For My Sunshine'
theme = 'PaperMod'

# --- БЛОК ПРИВАТНОСТІ ---

# 1. Вимикаємо генерацію карти сайту та RSS (щоб боти не знайшли лінки)
disableSitemap = true
disableRSS = true
disableKinds = ["RSS", "sitemap", "taxonomy", "term"]

# 2. Забороняємо індексацію для пошуковиків
[params]
  env = "production" # PaperMod використовує це для аналітики
  # Цей параметр додасть meta name="robots" content="noindex" у заголовок
  robots = "noindex, nofollow" 
  # ... інші налаштування ...
  analytics = { google = { SiteVerificationTag = "XYZ", GTag = "G-BQ7Y53BCDL" } }
  [params.label]
    text = "For My Sunshine"  <-- Це буде написано зліва зверху в меню
    icon = "/favicon.png"  <-- (можна навіть іконку додати, якщо є)

# Вимикаємо кнопку "Home" в меню, щоб випадковий гість бачив порожній екран
[menu]
